/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TiendaRouteImport } from './routes/tienda'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TiendaMisPedidosRouteImport } from './routes/tienda.mis-pedidos'
import { Route as TiendaCheckoutRouteImport } from './routes/tienda.checkout'
import { Route as AuthenticatedVentasProvinciaRouteImport } from './routes/_authenticated.ventas-provincia'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated.usuarios'
import { Route as AuthenticatedRolPagosRouteImport } from './routes/_authenticated.rol-pagos'
import { Route as AuthenticatedProveedoresRouteImport } from './routes/_authenticated.proveedores'
import { Route as AuthenticatedProductosRouteImport } from './routes/_authenticated.productos'
import { Route as AuthenticatedPlanCuentasRouteImport } from './routes/_authenticated.plan-cuentas'
import { Route as AuthenticatedOrdenesCompraRouteImport } from './routes/_authenticated.ordenes-compra'
import { Route as AuthenticatedFacturasRouteImport } from './routes/_authenticated.facturas'
import { Route as AuthenticatedEmpleadosRouteImport } from './routes/_authenticated.empleados'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated.clientes'
import { Route as AuthenticatedAuditoriaRouteImport } from './routes/_authenticated.auditoria'
import { Route as AuthenticatedAsientosRouteImport } from './routes/_authenticated.asientos'
import { Route as AuthenticatedAjustesInventarioRouteImport } from './routes/_authenticated.ajustes-inventario'
import { Route as AuthenticatedArqNubeRouteImport } from './routes/_authenticated.arq.nube'
import { Route as AuthenticatedArqNosqlRouteImport } from './routes/_authenticated.arq.nosql'
import { Route as AuthenticatedArqHibridaRouteImport } from './routes/_authenticated.arq.hibrida'
import { Route as AuthenticatedArqDistribuidaRouteImport } from './routes/_authenticated.arq.distribuida'
import { Route as AuthenticatedArqComparativaRouteImport } from './routes/_authenticated.arq.comparativa'
import { Route as AuthenticatedArqCentralizadaRouteImport } from './routes/_authenticated.arq.centralizada'

const TiendaRoute = TiendaRouteImport.update({
  id: '/tienda',
  path: '/tienda',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TiendaMisPedidosRoute = TiendaMisPedidosRouteImport.update({
  id: '/mis-pedidos',
  path: '/mis-pedidos',
  getParentRoute: () => TiendaRoute,
} as any)
const TiendaCheckoutRoute = TiendaCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => TiendaRoute,
} as any)
const AuthenticatedVentasProvinciaRoute =
  AuthenticatedVentasProvinciaRouteImport.update({
    id: '/ventas-provincia',
    path: '/ventas-provincia',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRolPagosRoute = AuthenticatedRolPagosRouteImport.update({
  id: '/rol-pagos',
  path: '/rol-pagos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProveedoresRoute =
  AuthenticatedProveedoresRouteImport.update({
    id: '/proveedores',
    path: '/proveedores',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProductosRoute = AuthenticatedProductosRouteImport.update({
  id: '/productos',
  path: '/productos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlanCuentasRoute =
  AuthenticatedPlanCuentasRouteImport.update({
    id: '/plan-cuentas',
    path: '/plan-cuentas',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrdenesCompraRoute =
  AuthenticatedOrdenesCompraRouteImport.update({
    id: '/ordenes-compra',
    path: '/ordenes-compra',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFacturasRoute = AuthenticatedFacturasRouteImport.update({
  id: '/facturas',
  path: '/facturas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEmpleadosRoute = AuthenticatedEmpleadosRouteImport.update({
  id: '/empleados',
  path: '/empleados',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuditoriaRoute = AuthenticatedAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAsientosRoute = AuthenticatedAsientosRouteImport.update({
  id: '/asientos',
  path: '/asientos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAjustesInventarioRoute =
  AuthenticatedAjustesInventarioRouteImport.update({
    id: '/ajustes-inventario',
    path: '/ajustes-inventario',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedArqNubeRoute = AuthenticatedArqNubeRouteImport.update({
  id: '/arq/nube',
  path: '/arq/nube',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedArqNosqlRoute = AuthenticatedArqNosqlRouteImport.update({
  id: '/arq/nosql',
  path: '/arq/nosql',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedArqHibridaRoute = AuthenticatedArqHibridaRouteImport.update({
  id: '/arq/hibrida',
  path: '/arq/hibrida',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedArqDistribuidaRoute =
  AuthenticatedArqDistribuidaRouteImport.update({
    id: '/arq/distribuida',
    path: '/arq/distribuida',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedArqComparativaRoute =
  AuthenticatedArqComparativaRouteImport.update({
    id: '/arq/comparativa',
    path: '/arq/comparativa',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedArqCentralizadaRoute =
  AuthenticatedArqCentralizadaRouteImport.update({
    id: '/arq/centralizada',
    path: '/arq/centralizada',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/tienda': typeof TiendaRouteWithChildren
  '/ajustes-inventario': typeof AuthenticatedAjustesInventarioRoute
  '/asientos': typeof AuthenticatedAsientosRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/empleados': typeof AuthenticatedEmpleadosRoute
  '/facturas': typeof AuthenticatedFacturasRoute
  '/ordenes-compra': typeof AuthenticatedOrdenesCompraRoute
  '/plan-cuentas': typeof AuthenticatedPlanCuentasRoute
  '/productos': typeof AuthenticatedProductosRoute
  '/proveedores': typeof AuthenticatedProveedoresRoute
  '/rol-pagos': typeof AuthenticatedRolPagosRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/ventas-provincia': typeof AuthenticatedVentasProvinciaRoute
  '/tienda/checkout': typeof TiendaCheckoutRoute
  '/tienda/mis-pedidos': typeof TiendaMisPedidosRoute
  '/arq/centralizada': typeof AuthenticatedArqCentralizadaRoute
  '/arq/comparativa': typeof AuthenticatedArqComparativaRoute
  '/arq/distribuida': typeof AuthenticatedArqDistribuidaRoute
  '/arq/hibrida': typeof AuthenticatedArqHibridaRoute
  '/arq/nosql': typeof AuthenticatedArqNosqlRoute
  '/arq/nube': typeof AuthenticatedArqNubeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/tienda': typeof TiendaRouteWithChildren
  '/ajustes-inventario': typeof AuthenticatedAjustesInventarioRoute
  '/asientos': typeof AuthenticatedAsientosRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/empleados': typeof AuthenticatedEmpleadosRoute
  '/facturas': typeof AuthenticatedFacturasRoute
  '/ordenes-compra': typeof AuthenticatedOrdenesCompraRoute
  '/plan-cuentas': typeof AuthenticatedPlanCuentasRoute
  '/productos': typeof AuthenticatedProductosRoute
  '/proveedores': typeof AuthenticatedProveedoresRoute
  '/rol-pagos': typeof AuthenticatedRolPagosRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/ventas-provincia': typeof AuthenticatedVentasProvinciaRoute
  '/tienda/checkout': typeof TiendaCheckoutRoute
  '/tienda/mis-pedidos': typeof TiendaMisPedidosRoute
  '/arq/centralizada': typeof AuthenticatedArqCentralizadaRoute
  '/arq/comparativa': typeof AuthenticatedArqComparativaRoute
  '/arq/distribuida': typeof AuthenticatedArqDistribuidaRoute
  '/arq/hibrida': typeof AuthenticatedArqHibridaRoute
  '/arq/nosql': typeof AuthenticatedArqNosqlRoute
  '/arq/nube': typeof AuthenticatedArqNubeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/tienda': typeof TiendaRouteWithChildren
  '/_authenticated/ajustes-inventario': typeof AuthenticatedAjustesInventarioRoute
  '/_authenticated/asientos': typeof AuthenticatedAsientosRoute
  '/_authenticated/auditoria': typeof AuthenticatedAuditoriaRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/empleados': typeof AuthenticatedEmpleadosRoute
  '/_authenticated/facturas': typeof AuthenticatedFacturasRoute
  '/_authenticated/ordenes-compra': typeof AuthenticatedOrdenesCompraRoute
  '/_authenticated/plan-cuentas': typeof AuthenticatedPlanCuentasRoute
  '/_authenticated/productos': typeof AuthenticatedProductosRoute
  '/_authenticated/proveedores': typeof AuthenticatedProveedoresRoute
  '/_authenticated/rol-pagos': typeof AuthenticatedRolPagosRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/_authenticated/ventas-provincia': typeof AuthenticatedVentasProvinciaRoute
  '/tienda/checkout': typeof TiendaCheckoutRoute
  '/tienda/mis-pedidos': typeof TiendaMisPedidosRoute
  '/_authenticated/arq/centralizada': typeof AuthenticatedArqCentralizadaRoute
  '/_authenticated/arq/comparativa': typeof AuthenticatedArqComparativaRoute
  '/_authenticated/arq/distribuida': typeof AuthenticatedArqDistribuidaRoute
  '/_authenticated/arq/hibrida': typeof AuthenticatedArqHibridaRoute
  '/_authenticated/arq/nosql': typeof AuthenticatedArqNosqlRoute
  '/_authenticated/arq/nube': typeof AuthenticatedArqNubeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/tienda'
    | '/ajustes-inventario'
    | '/asientos'
    | '/auditoria'
    | '/clientes'
    | '/dashboard'
    | '/empleados'
    | '/facturas'
    | '/ordenes-compra'
    | '/plan-cuentas'
    | '/productos'
    | '/proveedores'
    | '/rol-pagos'
    | '/usuarios'
    | '/ventas-provincia'
    | '/tienda/checkout'
    | '/tienda/mis-pedidos'
    | '/arq/centralizada'
    | '/arq/comparativa'
    | '/arq/distribuida'
    | '/arq/hibrida'
    | '/arq/nosql'
    | '/arq/nube'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/tienda'
    | '/ajustes-inventario'
    | '/asientos'
    | '/auditoria'
    | '/clientes'
    | '/dashboard'
    | '/empleados'
    | '/facturas'
    | '/ordenes-compra'
    | '/plan-cuentas'
    | '/productos'
    | '/proveedores'
    | '/rol-pagos'
    | '/usuarios'
    | '/ventas-provincia'
    | '/tienda/checkout'
    | '/tienda/mis-pedidos'
    | '/arq/centralizada'
    | '/arq/comparativa'
    | '/arq/distribuida'
    | '/arq/hibrida'
    | '/arq/nosql'
    | '/arq/nube'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/tienda'
    | '/_authenticated/ajustes-inventario'
    | '/_authenticated/asientos'
    | '/_authenticated/auditoria'
    | '/_authenticated/clientes'
    | '/_authenticated/dashboard'
    | '/_authenticated/empleados'
    | '/_authenticated/facturas'
    | '/_authenticated/ordenes-compra'
    | '/_authenticated/plan-cuentas'
    | '/_authenticated/productos'
    | '/_authenticated/proveedores'
    | '/_authenticated/rol-pagos'
    | '/_authenticated/usuarios'
    | '/_authenticated/ventas-provincia'
    | '/tienda/checkout'
    | '/tienda/mis-pedidos'
    | '/_authenticated/arq/centralizada'
    | '/_authenticated/arq/comparativa'
    | '/_authenticated/arq/distribuida'
    | '/_authenticated/arq/hibrida'
    | '/_authenticated/arq/nosql'
    | '/_authenticated/arq/nube'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  TiendaRoute: typeof TiendaRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tienda': {
      id: '/tienda'
      path: '/tienda'
      fullPath: '/tienda'
      preLoaderRoute: typeof TiendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tienda/mis-pedidos': {
      id: '/tienda/mis-pedidos'
      path: '/mis-pedidos'
      fullPath: '/tienda/mis-pedidos'
      preLoaderRoute: typeof TiendaMisPedidosRouteImport
      parentRoute: typeof TiendaRoute
    }
    '/tienda/checkout': {
      id: '/tienda/checkout'
      path: '/checkout'
      fullPath: '/tienda/checkout'
      preLoaderRoute: typeof TiendaCheckoutRouteImport
      parentRoute: typeof TiendaRoute
    }
    '/_authenticated/ventas-provincia': {
      id: '/_authenticated/ventas-provincia'
      path: '/ventas-provincia'
      fullPath: '/ventas-provincia'
      preLoaderRoute: typeof AuthenticatedVentasProvinciaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rol-pagos': {
      id: '/_authenticated/rol-pagos'
      path: '/rol-pagos'
      fullPath: '/rol-pagos'
      preLoaderRoute: typeof AuthenticatedRolPagosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/proveedores': {
      id: '/_authenticated/proveedores'
      path: '/proveedores'
      fullPath: '/proveedores'
      preLoaderRoute: typeof AuthenticatedProveedoresRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/productos': {
      id: '/_authenticated/productos'
      path: '/productos'
      fullPath: '/productos'
      preLoaderRoute: typeof AuthenticatedProductosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/plan-cuentas': {
      id: '/_authenticated/plan-cuentas'
      path: '/plan-cuentas'
      fullPath: '/plan-cuentas'
      preLoaderRoute: typeof AuthenticatedPlanCuentasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ordenes-compra': {
      id: '/_authenticated/ordenes-compra'
      path: '/ordenes-compra'
      fullPath: '/ordenes-compra'
      preLoaderRoute: typeof AuthenticatedOrdenesCompraRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/facturas': {
      id: '/_authenticated/facturas'
      path: '/facturas'
      fullPath: '/facturas'
      preLoaderRoute: typeof AuthenticatedFacturasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/empleados': {
      id: '/_authenticated/empleados'
      path: '/empleados'
      fullPath: '/empleados'
      preLoaderRoute: typeof AuthenticatedEmpleadosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/auditoria': {
      id: '/_authenticated/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuthenticatedAuditoriaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/asientos': {
      id: '/_authenticated/asientos'
      path: '/asientos'
      fullPath: '/asientos'
      preLoaderRoute: typeof AuthenticatedAsientosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ajustes-inventario': {
      id: '/_authenticated/ajustes-inventario'
      path: '/ajustes-inventario'
      fullPath: '/ajustes-inventario'
      preLoaderRoute: typeof AuthenticatedAjustesInventarioRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/arq/nube': {
      id: '/_authenticated/arq/nube'
      path: '/arq/nube'
      fullPath: '/arq/nube'
      preLoaderRoute: typeof AuthenticatedArqNubeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/arq/nosql': {
      id: '/_authenticated/arq/nosql'
      path: '/arq/nosql'
      fullPath: '/arq/nosql'
      preLoaderRoute: typeof AuthenticatedArqNosqlRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/arq/hibrida': {
      id: '/_authenticated/arq/hibrida'
      path: '/arq/hibrida'
      fullPath: '/arq/hibrida'
      preLoaderRoute: typeof AuthenticatedArqHibridaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/arq/distribuida': {
      id: '/_authenticated/arq/distribuida'
      path: '/arq/distribuida'
      fullPath: '/arq/distribuida'
      preLoaderRoute: typeof AuthenticatedArqDistribuidaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/arq/comparativa': {
      id: '/_authenticated/arq/comparativa'
      path: '/arq/comparativa'
      fullPath: '/arq/comparativa'
      preLoaderRoute: typeof AuthenticatedArqComparativaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/arq/centralizada': {
      id: '/_authenticated/arq/centralizada'
      path: '/arq/centralizada'
      fullPath: '/arq/centralizada'
      preLoaderRoute: typeof AuthenticatedArqCentralizadaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAjustesInventarioRoute: typeof AuthenticatedAjustesInventarioRoute
  AuthenticatedAsientosRoute: typeof AuthenticatedAsientosRoute
  AuthenticatedAuditoriaRoute: typeof AuthenticatedAuditoriaRoute
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEmpleadosRoute: typeof AuthenticatedEmpleadosRoute
  AuthenticatedFacturasRoute: typeof AuthenticatedFacturasRoute
  AuthenticatedOrdenesCompraRoute: typeof AuthenticatedOrdenesCompraRoute
  AuthenticatedPlanCuentasRoute: typeof AuthenticatedPlanCuentasRoute
  AuthenticatedProductosRoute: typeof AuthenticatedProductosRoute
  AuthenticatedProveedoresRoute: typeof AuthenticatedProveedoresRoute
  AuthenticatedRolPagosRoute: typeof AuthenticatedRolPagosRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
  AuthenticatedVentasProvinciaRoute: typeof AuthenticatedVentasProvinciaRoute
  AuthenticatedArqCentralizadaRoute: typeof AuthenticatedArqCentralizadaRoute
  AuthenticatedArqComparativaRoute: typeof AuthenticatedArqComparativaRoute
  AuthenticatedArqDistribuidaRoute: typeof AuthenticatedArqDistribuidaRoute
  AuthenticatedArqHibridaRoute: typeof AuthenticatedArqHibridaRoute
  AuthenticatedArqNosqlRoute: typeof AuthenticatedArqNosqlRoute
  AuthenticatedArqNubeRoute: typeof AuthenticatedArqNubeRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAjustesInventarioRoute: AuthenticatedAjustesInventarioRoute,
  AuthenticatedAsientosRoute: AuthenticatedAsientosRoute,
  AuthenticatedAuditoriaRoute: AuthenticatedAuditoriaRoute,
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEmpleadosRoute: AuthenticatedEmpleadosRoute,
  AuthenticatedFacturasRoute: AuthenticatedFacturasRoute,
  AuthenticatedOrdenesCompraRoute: AuthenticatedOrdenesCompraRoute,
  AuthenticatedPlanCuentasRoute: AuthenticatedPlanCuentasRoute,
  AuthenticatedProductosRoute: AuthenticatedProductosRoute,
  AuthenticatedProveedoresRoute: AuthenticatedProveedoresRoute,
  AuthenticatedRolPagosRoute: AuthenticatedRolPagosRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
  AuthenticatedVentasProvinciaRoute: AuthenticatedVentasProvinciaRoute,
  AuthenticatedArqCentralizadaRoute: AuthenticatedArqCentralizadaRoute,
  AuthenticatedArqComparativaRoute: AuthenticatedArqComparativaRoute,
  AuthenticatedArqDistribuidaRoute: AuthenticatedArqDistribuidaRoute,
  AuthenticatedArqHibridaRoute: AuthenticatedArqHibridaRoute,
  AuthenticatedArqNosqlRoute: AuthenticatedArqNosqlRoute,
  AuthenticatedArqNubeRoute: AuthenticatedArqNubeRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface TiendaRouteChildren {
  TiendaCheckoutRoute: typeof TiendaCheckoutRoute
  TiendaMisPedidosRoute: typeof TiendaMisPedidosRoute
}

const TiendaRouteChildren: TiendaRouteChildren = {
  TiendaCheckoutRoute: TiendaCheckoutRoute,
  TiendaMisPedidosRoute: TiendaMisPedidosRoute,
}

const TiendaRouteWithChildren =
  TiendaRoute._addFileChildren(TiendaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  TiendaRoute: TiendaRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
